version: "3.9"

services:
  chat-app:
    build: .
    container_name: chat-app
    ports:
      - "9000:9000"       # map container port 9000 to host
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - redis-server
    environment:
      - NODE_ENV=development

  redis-server:
    image: redis:6.2
    container_name: redis-server
    ports:
      - "6379:6379"
